# Generated by Django 5.0 on 2025-03-18 01:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesafioTempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do equipamento', max_length=50, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(50)], verbose_name='Nome')),
                ('data_inicio', models.DateField(help_text='Selecione o inicio', verbose_name='Inicio')),
                ('data_fim', models.DateField(help_text='Selecione o inicio', verbose_name='Inicio')),
                ('tipo_esporte', models.CharField(choices=[('RUN', 'Corrida'), ('TRUN', 'Corrida de Trilhas'), ('BIK', 'Treino de Bicicleta'), ('WAL', 'Caminhada'), ('HIT', 'Treino de Alta Intensidade'), ('STR', 'Treino de Força'), ('CAR', 'Treino Aeróbico'), ('SWM', 'Natação')], help_text='Selecione o Esporte', max_length=5, verbose_name='Esporte')),
                ('visao_geral', models.TextField(help_text='Digite o texto', verbose_name='Visão Geral')),
                ('selo', models.CharField(help_text='Digite o selo', max_length=5, verbose_name='Selo')),
                ('meta_duracao', models.TimeField(help_text='Digite a meta', verbose_name='Meta')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
