# Generated by Django 5.0 on 2025-04-07 23:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Digite o nome', max_length=100, verbose_name='Nome')),
                ('pub_date', models.DateField(default='Digite a data', help_text='Digite a data', verbose_name='Data da publicação')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Digite o nome', max_length=100, verbose_name='Nome')),
                ('edition', models.IntegerField(default='1', help_text='Digite qual a edição', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Edição')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Digite o nome', max_length=100, verbose_name='Nome')),
                ('birth_date', models.DateField(default='', help_text='Digite a data', verbose_name='Data de aniversário')),
                ('cpf', models.CharField(help_text='Digite o CPF', max_length=11, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.MaxLengthValidator(11)], verbose_name='CPF')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Digite o nome', max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(help_text='Email exemplo', max_length=254, unique=True, verbose_name='E-mail')),
                ('cpf', models.CharField(help_text='Digite o CPF', max_length=11, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.MaxLengthValidator(11)], verbose_name='CPF')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('number', models.CharField(help_text='Digite os dígitos do passaporte', max_length=8, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(8)], verbose_name=' Dígitos do Passaporte')),
                ('issue_date', models.DateField(default='', help_text='Digite a data', verbose_name='Data de Expedição')),
                ('expiration_date', models.DateField(default='', help_text='Digite a data', verbose_name='Data de Expiração')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='aula.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('obs', models.TextField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='aula.article')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='aula.person')),
                ('magazine', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='aula.magazine')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='article',
            name='magazines',
            field=models.ManyToManyField(blank=True, null=True, through='aula.Publication', to='aula.magazine'),
        ),
        migrations.AddField(
            model_name='article',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aula.reporter'),
        ),
    ]
