# Generated by Django 5.0 on 2025-03-24 23:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Digite o nome', max_length=100, verbose_name='Nome')),
                ('birth_date', models.DateField(auto_now_add=True, help_text='Digite a data', verbose_name='Data de aniversário')),
                ('cpf', models.CharField(help_text='Digite o CPF', max_length=11, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.MaxLengthValidator(11)], verbose_name='CPF')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('number', models.CharField(help_text='Digite os dígitos do passaporte', max_length=8, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(8)], verbose_name=' Dígitos do Passaporte')),
                ('issue_date', models.DateField(auto_now_add=True, help_text='Digite a data', verbose_name='Data de Expedição')),
                ('expiration_date', models.DateField(auto_now_add=True, help_text='Digite a data', verbose_name='Data de Expiração')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='aula.person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
