# Generated by Django 5.0 on 2025-03-25 00:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Digite o nome', max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(help_text='Email exemplo', max_length=254, unique=True, verbose_name='E-mail')),
                ('cpf', models.CharField(help_text='Digite o CPF', max_length=11, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.MaxLengthValidator(11)], verbose_name='CPF')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='passport',
            name='expiration_date',
            field=models.DateField(default='', help_text='Digite a data', verbose_name='Data de Expiração'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='issue_date',
            field=models.DateField(default='', help_text='Digite a data', verbose_name='Data de Expedição'),
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(default='', help_text='Digite a data', verbose_name='Data de aniversário'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Digite o nome', max_length=100, verbose_name='Nome')),
                ('pub_date', models.DateField(default='Digite a data', help_text='Digite a data', verbose_name='Data da publicação')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aula.reporter')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
