# Generated by Django 5.0 on 2025-04-08 01:22

import aula.validators.cod
import aula.validators.funcoes
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exemplo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(blank=True, max_length=10, validators=[django.core.validators.MinLengthValidator(10), aula.validators.cod.CodValidator('4444444444'), aula.validators.funcoes.validate_par])),
                ('nome', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(3)])),
                ('people', models.ManyToManyField(blank=True, null=True, to='aula.person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
