# Generated by Django 5.0 on 2025-06-17 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0002_exemplo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exemplo',
            options={'permissions': [('generate_code_exemplo', 'can generate new codes')]},
        ),
    ]
