# Generated by Django 5.0 on 2025-03-25 00:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0002_reporter_alter_passport_expiration_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Digite o nome', max_length=100, verbose_name='Nome')),
                ('edition', models.IntegerField(default='1', help_text='Digite qual a edição', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Edição')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='article',
            name='magazines',
            field=models.ManyToManyField(to='aula.magazine'),
        ),
    ]
